### ISSUE TITLE
Beta 2

### ISSUE THREAD

**Issue by Luxcium** [Luxcium/questrade-ts#48]
# Working on releasing version BETA-2.0.0c 

### TODO

- [ ] Documentation
- [ ] Test suites
- [ ] Custom error logging
- [ ]  Segregating business logic from side effects 
- [ ] Proxi integration for Redis
- [ ] Proxi integration for MongoDB (with Mongoose)
 
### ACCOUNT CALLS 

`account.currentAccount: string`

 - [X] GET ACCOUNTS/:ID/BALANCES
    `qtApi.account.getBalances(): Promise<IBalances>`
 - [X] GET ACCOUNTS
    `qtApi.account.getAllAccounts(): Promise<IAccount[]>`
 - [X] GET ACCOUNTS/:ID/ACTIVITIES
   `account.getActivities: DateRange<Promise<IAccountActivity[]>>`
 - [X] GET ACCOUNTS/:ID/ORDERS
    `account.getOrders(stateFilter?: string | undefined): DateRange<Promise<IOrder[]>>`
    `account.getOrdersByIds(orderIds: number[]): Promise<IOrder[]>`
 - [X] GET ACCOUNTS/:ID/EXECUTIONS
    `account.getExecutions: DateRange<Promise<IExecution[]>>`
 - [X] GET ACCOUNTS/:ID/POSITIONS
   `account.getPositions(): Promise<IPosition[]>`
 - [X] GET TIME
   `account.getServerTime(): Promise<Date>`

### Types 

`DateRange<R> = (startTime: string) => (endTime: string) => R`
